### ISSUE TITLE
llm_pretrain预训练数据样例有吗，可以提供个样例数据吗

### ISSUE THREAD

**Issue by sxk000** [xyjigsaw/LLM-Pretrain-SFT#2]
你好，llm_pretrain预训练数据样例有吗，可以提供个样例数据吗？谢谢分享！

**Comment by xyjigsaw** [comment]
这个repo下有样例数据的：[examples](https://github.com/xyjigsaw/LLM-Pretrain-SFT/blob/master/llm_pretrain/data/A_Guide_to_Writing_the_NeurIPS_Impact_Statement.md)

可以把多个txt或者md文件放到data文件夹下，脚本会自动读入所有文本数据的。
